# Generated by Django 4.1.6 on 2023-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_data_options_device_deployment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.CharField(help_text='comma separated parameters', max_length=200)),
            ],
        ),
    ]
