# Generated by Django 4.1.6 on 2023-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_paramgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramgroup',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
