# Generated by Django 4.1.6 on 2023-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_daysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='battery_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='dp_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='internal_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='leaf_wetness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='reset_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sm1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sm2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
