# Generated by Django 4.1.6 on 2023-06-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_weatherforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together={('device', 'recorded_date', 'date', 'param')},
        ),
    ]
