# Generated by Django 4.1.6 on 2023-06-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_weatherforecast_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daysummary',
            unique_together={('device', 'date', 'param')},
        ),
    ]
