# Generated by Django 4.1.6 on 2023-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_daysummary_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(help_text='parameter name', max_length=200, unique=True)),
                ('unit', models.CharField(max_length=30)),
                ('min_limit', models.FloatField()),
                ('max_limit', models.FloatField()),
            ],
        ),
    ]
