# Generated by Django 4.1.6 on 2023-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_paramconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramconfig',
            name='max_expected_delta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
