# Generated by Django 4.1.6 on 2023-10-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_paramconfig_max_expected_delta'),
        ('farmer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.device')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_dashboard.farmer')),
            ],
        ),
    ]
