# Generated by Django 4.1.6 on 2023-10-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_paramconfig_max_expected_delta'),
        ('farmer_dashboard', '0002_farmerdevicemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.device'),
        ),
    ]
