# Generated by Django 4.1.6 on 2023-10-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0003_crop_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerDeviceMapping',
        ),
    ]
