# Generated by Django 4.1.6 on 2023-10-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0004_delete_farmerdevicemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='icon',
            field=models.ImageField(upload_to='farmer_dashboard/crop_icons/'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='wms_background',
            field=models.FileField(upload_to='farmer_dashboard/wms_backgrounds/'),
        ),
    ]
