# Generated by Django 4.1.6 on 2023-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0005_alter_croptype_icon_alter_croptype_wms_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='icon',
            field=models.ImageField(upload_to='static/farmer_dashboard/assets/crop_icons/'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='wms_background',
            field=models.FileField(upload_to='static/farmer_dashboard/assets/wms_backgrounds/'),
        ),
    ]
