# Generated by Django 4.1.6 on 2023-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0007_farmer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='Yield_predicted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='date_of_planting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='total_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='flowering_phase',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/total_growth_card/'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='ready_to_harvest',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/total_growth_card/'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='ripening_phase',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/total_growth_card/'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='seed_phase',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/total_growth_card/'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='seedling_phase',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/total_growth_card/'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='icon',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/crop_icons/'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='wms_background',
            field=models.FileField(null=True, upload_to='static/farmer_dashboard/assets/wms_backgrounds/'),
        ),
    ]
