# Generated by Django 4.1.6 on 2024-01-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0008_crop_yield_predicted_crop_date_of_planting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='Tb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
