# Generated by Django 4.1.6 on 2024-01-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0009_croptype_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tb', models.FloatField(blank=True, choices=[(10, '10 for khari'), (5, '5 for rabi')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='croptype',
            name='Tb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_dashboard.yourmodel'),
        ),
    ]
