# Generated by Django 4.1.6 on 2024-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0010_yourmodel_alter_croptype_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='Tb',
            field=models.CharField(blank=True, choices=[('KHARI', '10 for khari'), ('RABI', '5 for rabi')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
