# Generated by Django 4.1.6 on 2024-01-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0011_alter_croptype_tb_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='Tb',
            field=models.IntegerField(blank=True, choices=[(10, '10 for kharif'), (5, '5 for rabi')], null=True),
        ),
    ]
