# Generated by Django 4.1.6 on 2024-01-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0012_alter_croptype_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croptype',
            old_name='ready_to_harvest',
            new_name='vegetative_phase',
        ),
    ]
