# Generated by Django 4.1.6 on 2024-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0013_rename_ready_to_harvest_croptype_vegetative_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='flowering_phase_gdd_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='ripening_phase_gdd_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='seed_phase_gdd_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='seedling_phase_gdd_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='vegetative_phase_gdd_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
