# Generated by Django 4.1.6 on 2024-02-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0014_croptype_flowering_phase_gdd_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gdd_value', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdd_records', to='farmer_dashboard.crop')),
            ],
            options={
                'unique_together': {('crop', 'date')},
            },
        ),
    ]
