# Generated by Django 4.1.6 on 2024-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0015_gddrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='has_flowering_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croptype',
            name='has_ripening_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croptype',
            name='has_seed_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croptype',
            name='has_seedling_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='croptype',
            name='has_vegetative_stage',
            field=models.BooleanField(default=False),
        ),
    ]
