# Generated by Django 4.1.6 on 2024-02-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0016_croptype_has_flowering_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='wms_background',
            field=models.ImageField(null=True, upload_to='static/farmer_dashboard/assets/wms_backgrounds/'),
        ),
    ]
