# Generated by Django 4.1.6 on 2024-03-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0017_alter_croptype_wms_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Weather', 'Weather Alerts'), ('Irrigation', 'Irrigation Alerts'), ('Pest', 'Pest Alerts'), ('Disease', 'Disease Alerts'), ('Soil Health', 'Soil Health Alerts'), ('Equipment Maintenance', 'Equipment Maintenance Alerts'), ('Government Policy', 'Government Policy and Regulation Alerts'), ('Market Trends', 'Market Trends and News Alerts'), ('Harvest', 'Harvest Alerts'), ('Planting', 'Planting Alerts'), ('Heat', 'Heat Alerts'), ('Environmental Impact', 'Environmental Impact Alerts'), ('Government Support', 'Government Support Alerts'), ('Security', 'Security Alerts')], max_length=100)),
                ('description', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farmer_dashboard.crop')),
            ],
        ),
    ]
