# Generated by Django 4.1.6 on 2024-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0018_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
