# Generated by Django 4.1.6 on 2024-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0019_alert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='date',
        ),
        migrations.AddField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
